# Generated by Django 5.2.15 on 2026-06-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Login success"),
                    ("login_failed", "Login failed"),
                    ("logout", "Logout"),
                    ("password_changed", "Password changed"),
                    ("temporary_password_set", "Temporary password set"),
                    ("account_created", "Account created"),
                    ("account_updated", "Account updated"),
                    ("account_deactivated", "Account deactivated"),
                    ("account_reactivated", "Account reactivated"),
                    ("role_changed", "Role changed"),
                    ("location_created", "Location created"),
                    ("location_updated", "Location updated"),
                    ("location_deactivated", "Location deactivated"),
                    ("location_reactivated", "Location reactivated"),
                    ("work_area_created", "Work area created"),
                    ("work_area_updated", "Work area updated"),
                    ("work_area_deactivated", "Work area deactivated"),
                    ("work_area_reactivated", "Work area reactivated"),
                    ("work_category_created", "Work category created"),
                    ("work_category_updated", "Work category updated"),
                    ("work_category_deactivated", "Work category deactivated"),
                    ("work_category_reactivated", "Work category reactivated"),
                    ("work_type_created", "Work type created"),
                    ("work_type_updated", "Work type updated"),
                    ("work_type_deactivated", "Work type deactivated"),
                    ("work_type_reactivated", "Work type reactivated"),
                    ("work_type_availability_created", "Work type availability created"),
                    ("work_type_availability_updated", "Work type availability updated"),
                    ("work_type_availability_deactivated", "Work type availability deactivated"),
                    ("work_type_availability_reactivated", "Work type availability reactivated"),
                    ("staff_location_created", "Staff location created"),
                    ("staff_location_updated", "Staff location updated"),
                    ("staff_location_deactivated", "Staff location deactivated"),
                    ("staff_location_reactivated", "Staff location reactivated"),
                    ("staff_capability_created", "Staff capability created"),
                    ("staff_capability_updated", "Staff capability updated"),
                    ("staff_capability_deactivated", "Staff capability deactivated"),
                    ("staff_capability_reactivated", "Staff capability reactivated"),
                ],
                max_length=64,
            ),
        ),
    ]
