# Generated by Django 5.2.15 on 2026-06-20 23:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("timezone", models.CharField(default="Asia/Tokyo", max_length=64)),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Work category",
                "verbose_name_plural": "Work categories",
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkArea",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="work_areas", to="operations.location"
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("default_duration_minutes", models.PositiveIntegerField(default=60)),
                ("minimum_staff_count", models.PositiveIntegerField(default=1)),
                ("maximum_staff_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "color_key",
                    models.CharField(
                        choices=[
                            ("slate", "slate"),
                            ("blue", "blue"),
                            ("green", "green"),
                            ("amber", "amber"),
                            ("red", "red"),
                            ("violet", "violet"),
                            ("cyan", "cyan"),
                            ("pink", "pink"),
                        ],
                        default="slate",
                        max_length=20,
                    ),
                ),
                ("requires_capability", models.BooleanField(default=False)),
                ("can_overlap", models.BooleanField(default=False)),
                ("is_break", models.BooleanField(default=False)),
                ("is_bookable", models.BooleanField(default=False)),
                ("requires_customer", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_types",
                        to="operations.workcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work type",
                "verbose_name_plural": "Work types",
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffCapability",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("trainee", "trainee"),
                            ("assisted", "assisted"),
                            ("independent", "independent"),
                            ("trainer", "trainer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_staff_capabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_capabilities",
                        to="operations.location",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_capabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_capabilities",
                        to="operations.worktype",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkTypeAvailability",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_type_availabilities",
                        to="operations.location",
                    ),
                ),
                (
                    "work_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_type_availabilities",
                        to="operations.workarea",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="availabilities",
                        to="operations.worktype",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffLocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_locations",
                        to="operations.location",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "location", "valid_from", "valid_until"), name="unique_staff_location_period"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="workarea",
            constraint=models.UniqueConstraint(fields=("location", "code"), name="unique_work_area_code_per_location"),
        ),
        migrations.AddConstraint(
            model_name="staffcapability",
            constraint=models.UniqueConstraint(
                fields=("staff", "work_type", "location", "valid_from", "valid_until"),
                name="unique_staff_capability_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="worktypeavailability",
            constraint=models.UniqueConstraint(
                fields=("work_type", "location", "work_area"), name="unique_work_type_availability"
            ),
        ),
    ]
