# Generated by Django 5.2.15 on 2026-06-21 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="staffcapability",
            name="unique_staff_capability_period",
        ),
        migrations.RemoveConstraint(
            model_name="stafflocation",
            name="unique_staff_location_period",
        ),
        migrations.RemoveConstraint(
            model_name="worktypeavailability",
            name="unique_work_type_availability",
        ),
        migrations.AddConstraint(
            model_name="staffcapability",
            constraint=models.UniqueConstraint(
                fields=("staff", "work_type", "location", "valid_from", "valid_until"),
                name="unique_staff_capability_period",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="stafflocation",
            constraint=models.UniqueConstraint(
                fields=("staff", "location", "valid_from", "valid_until"),
                name="unique_staff_location_period",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="worktype",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_duration_minutes__gt", 0)), name="work_type_duration_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="worktype",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_staff_count__gte", 1)), name="work_type_minimum_staff_at_least_one"
            ),
        ),
        migrations.AddConstraint(
            model_name="worktype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum_staff_count__isnull", True),
                    ("maximum_staff_count__gte", models.F("minimum_staff_count")),
                    _connector="OR",
                ),
                name="work_type_maximum_staff_gte_minimum",
            ),
        ),
        migrations.AddConstraint(
            model_name="worktypeavailability",
            constraint=models.UniqueConstraint(
                fields=("work_type", "location", "work_area"),
                name="unique_work_type_availability",
                nulls_distinct=False,
            ),
        ),
    ]
