# Generated by Django 5.2.15 on 2026-06-23 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("operations", "0002_remove_staffcapability_unique_staff_capability_period_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftPattern",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=150)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_patterns",
                        to="operations.location",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShiftPatternSegment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("start_offset_minutes", models.PositiveIntegerField()),
                ("end_offset_minutes", models.PositiveIntegerField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shift_pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="segments", to="shifts.shiftpattern"
                    ),
                ),
                (
                    "work_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_pattern_segments",
                        to="operations.workarea",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_pattern_segments",
                        to="operations.worktype",
                    ),
                ),
            ],
            options={
                "ordering": ["start_offset_minutes", "display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyShiftTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_shift_templates",
                        to="operations.location",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeeklyShiftTemplateEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shift_pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_template_entries",
                        to="shifts.shiftpattern",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_shift_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weekly_shift_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="shifts.weeklyshifttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["staff__display_name", "weekday", "display_order", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="shiftpattern",
            constraint=models.UniqueConstraint(
                fields=("location", "code"), name="unique_shift_pattern_code_per_location"
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftpatternsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_offset_minutes__gte", 0), ("start_offset_minutes__lt", 2880)),
                name="shift_segment_start_offset_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftpatternsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_offset_minutes__gt", 0), ("end_offset_minutes__lte", 2880)),
                name="shift_segment_end_offset_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftpatternsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_offset_minutes__gt", models.F("start_offset_minutes"))),
                name="shift_segment_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyshifttemplate",
            constraint=models.UniqueConstraint(
                fields=("location", "code"), name="unique_weekly_template_code_per_location"
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyshifttemplateentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)), name="weekly_entry_weekday_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyshifttemplateentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("weekly_shift_template", "weekday", "staff"),
                name="unique_active_weekly_entry_per_staff_weekday",
            ),
        ),
    ]
