# Generated by Django 5.2.15 on 2026-06-23 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_remove_staffcapability_unique_staff_capability_period_and_more"),
        ("shifts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyShiftPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=150)),
                ("notes", models.TextField(blank=True)),
                ("last_generated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_plans_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_plans",
                        to="operations.location",
                    ),
                ),
                (
                    "source_weekly_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_monthly_shift_plans",
                        to="shifts.weeklyshifttemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_plans_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "location__display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyShiftAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("work_date", models.DateField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[("template", "template"), ("manual", "manual")], default="manual", max_length=20
                    ),
                ),
                ("pattern_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("pattern_name_snapshot", models.CharField(blank=True, max_length=150)),
                ("pattern_short_name_snapshot", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_customized", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_shift_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_assignments",
                        to="shifts.shiftpattern",
                    ),
                ),
                (
                    "source_weekly_template_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_assignments",
                        to="shifts.weeklyshifttemplateentry",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_assignments_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monthly_shift_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="shifts.monthlyshiftplan",
                    ),
                ),
            ],
            options={
                "ordering": ["work_date", "display_order", "staff__display_name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyShiftSegment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("work_type_name_snapshot", models.CharField(max_length=150)),
                ("work_type_short_name_snapshot", models.CharField(max_length=100)),
                ("work_type_color_key_snapshot", models.CharField(max_length=20)),
                ("work_type_is_break_snapshot", models.BooleanField(default=False)),
                ("work_area_name_snapshot", models.CharField(blank=True, max_length=150)),
                ("start_offset_minutes", models.IntegerField()),
                ("end_offset_minutes", models.IntegerField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monthly_shift_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segments",
                        to="shifts.monthlyshiftassignment",
                    ),
                ),
                (
                    "source_pattern_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_segments",
                        to="shifts.shiftpatternsegment",
                    ),
                ),
                (
                    "work_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_segments",
                        to="operations.workarea",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_segments",
                        to="operations.worktype",
                    ),
                ),
            ],
            options={
                "ordering": ["start_offset_minutes", "display_order", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="monthlyshiftplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 2000), ("year__lte", 2100)), name="monthly_plan_year_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyshiftplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)), name="monthly_plan_month_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyshiftplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("location", "year", "month"),
                name="unique_active_monthly_plan_location_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyshiftassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("monthly_shift_plan", "work_date", "staff"),
                name="unique_active_monthly_assignment_cell",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyshiftsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_offset_minutes__gte", 0), ("start_offset_minutes__lt", 2880)),
                name="monthly_segment_start_offset_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyshiftsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_offset_minutes__gt", 0), ("end_offset_minutes__lte", 2880)),
                name="monthly_segment_end_offset_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyshiftsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_offset_minutes__gt", models.F("start_offset_minutes"))),
                name="monthly_segment_end_after_start",
            ),
        ),
    ]
