# Generated by Django 5.2.15 on 2026-06-26 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_remove_staffcapability_unique_staff_capability_period_and_more"),
        ("shifts", "0002_monthlyshiftplan_monthlyshiftassignment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyshiftplan",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monthlyshiftplan",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="monthly_shift_plans_confirmed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monthlyshiftplan",
            name="confirmed_content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="monthlyshiftplan",
            name="workflow_status",
            field=models.CharField(
                choices=[("draft", "draft"), ("confirmed", "confirmed"), ("published", "published")],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MonthlyShiftPublication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("content_hash", models.CharField(max_length=64)),
                ("location_name_snapshot", models.CharField(max_length=150)),
                ("location_short_name_snapshot", models.CharField(max_length=100)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("plan_name_snapshot", models.CharField(max_length=150)),
                ("plan_notes_snapshot", models.TextField(blank=True)),
                ("published_at", models.DateTimeField()),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_publications",
                        to="operations.location",
                    ),
                ),
                (
                    "monthly_shift_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publications",
                        to="shifts.monthlyshiftplan",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_publications_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_publications_withdrawn",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-version"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyShiftPublicationAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("work_date", models.DateField()),
                ("staff_display_name_snapshot", models.CharField(max_length=150)),
                ("employee_code_snapshot", models.CharField(blank=True, max_length=50)),
                (
                    "source_type",
                    models.CharField(choices=[("template", "template"), ("manual", "manual")], max_length=20),
                ),
                ("is_customized", models.BooleanField(default=False)),
                ("pattern_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("pattern_name_snapshot", models.CharField(blank=True, max_length=150)),
                ("pattern_short_name_snapshot", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("warning_count_snapshot", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="shifts.monthlyshiftpublication",
                    ),
                ),
                (
                    "source_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_snapshots",
                        to="shifts.monthlyshiftassignment",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_publication_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["work_date", "display_order", "employee_code_snapshot", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyShiftPublicationSegment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("work_type_name_snapshot", models.CharField(max_length=150)),
                ("work_type_short_name_snapshot", models.CharField(max_length=100)),
                ("work_type_color_key_snapshot", models.CharField(max_length=20)),
                ("work_type_is_break_snapshot", models.BooleanField(default=False)),
                ("work_area_name_snapshot", models.CharField(blank=True, max_length=150)),
                ("start_offset_minutes", models.IntegerField()),
                ("end_offset_minutes", models.IntegerField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segments",
                        to="shifts.monthlyshiftpublicationassignment",
                    ),
                ),
                (
                    "source_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_snapshots",
                        to="shifts.monthlyshiftsegment",
                    ),
                ),
                (
                    "work_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_publication_segments",
                        to="operations.workarea",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_shift_publication_segments",
                        to="operations.worktype",
                    ),
                ),
            ],
            options={
                "ordering": ["start_offset_minutes", "display_order", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="monthlyshiftpublication",
            constraint=models.UniqueConstraint(
                fields=("monthly_shift_plan", "version"), name="unique_monthly_shift_publication_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyshiftpublication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("monthly_shift_plan",),
                name="unique_active_monthly_shift_publication",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyshiftpublicationassignment",
            constraint=models.UniqueConstraint(
                fields=("publication", "work_date", "staff"), name="unique_publication_assignment_cell"
            ),
        ),
    ]
