# Generated by Django 5.2.15 on 2026-07-10 03:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_remove_staffcapability_unique_staff_capability_period_and_more"),
        ("shifts", "0003_monthlyshiftplan_confirmed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftRequestPeriod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("opens_at", models.DateTimeField()),
                ("closes_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("open", "open"), ("closed", "closed"), ("archived", "archived")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_request_periods_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_request_periods",
                        to="operations.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_request_periods_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "location__display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftRequestSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("returned", "returned"),
                            ("locked", "locked"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("return_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="shifts.shiftrequestperiod",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_request_submissions_returned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_request_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_request_submissions_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["request_period", "staff__display_name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftRequestItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("day_off", "day_off"),
                            ("unavailable", "unavailable"),
                            ("prefer_work", "prefer_work"),
                            ("prefer_time", "prefer_time"),
                            ("note", "note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("work_date", models.DateField(blank=True, null=True)),
                ("start_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("end_offset_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "high"), ("normal", "normal"), ("low", "low")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "work_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_request_items",
                        to="operations.workarea",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_request_items",
                        to="operations.worktype",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="shifts.shiftrequestsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["work_date", "start_offset_minutes", "request_type", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="shiftrequestperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("location", "year", "month"),
                name="unique_active_shift_request_period_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftrequestsubmission",
            constraint=models.UniqueConstraint(
                fields=("request_period", "staff"), name="unique_shift_request_submission_staff"
            ),
        ),
    ]
