# Generated by Django 5.2.15 on 2026-07-13 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_remove_staffcapability_unique_staff_capability_period_and_more"),
        ("shifts", "0004_shiftrequestperiod_shiftrequestsubmission_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftChangeRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("drop_shift", "drop_shift"),
                            ("swap_shift", "swap_shift"),
                            ("cover_request", "cover_request"),
                            ("change_time", "change_time"),
                            ("change_assignment", "change_assignment"),
                            ("manager_adjustment", "manager_adjustment"),
                            ("note", "note"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("cancelled", "cancelled"),
                            ("applied", "applied"),
                            ("closed", "closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "high"), ("normal", "normal"), ("low", "low")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("work_date", models.DateField()),
                ("original_start_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("original_end_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("original_pattern_name_snapshot", models.CharField(blank=True, max_length=150)),
                ("original_pattern_short_name_snapshot", models.CharField(blank=True, max_length=100)),
                ("requested_work_date", models.DateField(blank=True, null=True)),
                ("requested_start_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("requested_end_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("requested_notes", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                ("manager_note", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests",
                        to="operations.location",
                    ),
                ),
                (
                    "monthly_shift_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests",
                        to="shifts.monthlyshiftplan",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests",
                        to="shifts.monthlyshiftpublication",
                    ),
                ),
                (
                    "publication_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests",
                        to="shifts.monthlyshiftpublicationassignment",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_shift_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests",
                        to="shifts.shiftpattern",
                    ),
                ),
                (
                    "requested_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests_requested_as_cover",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_change_requests_targeted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["location", "work_date"], name="shift_change_location_date_idx"),
                    models.Index(fields=["status", "request_type"], name="shift_change_status_type_idx"),
                    models.Index(fields=["requester", "work_date"], name="shift_chg_requester_dt_idx"),
                    models.Index(fields=["target_staff", "work_date"], name="shift_change_target_date_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("original_start_offset_minutes__isnull", True),
                            models.Q(
                                ("original_start_offset_minutes__gte", 0), ("original_start_offset_minutes__lt", 2880)
                            ),
                            _connector="OR",
                        ),
                        name="shift_change_original_start_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("original_end_offset_minutes__isnull", True),
                            models.Q(
                                ("original_end_offset_minutes__gt", 0), ("original_end_offset_minutes__lte", 2880)
                            ),
                            _connector="OR",
                        ),
                        name="shift_change_original_end_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("requested_start_offset_minutes__isnull", True),
                            models.Q(
                                ("requested_start_offset_minutes__gte", 0), ("requested_start_offset_minutes__lt", 2880)
                            ),
                            _connector="OR",
                        ),
                        name="shift_change_requested_start_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("requested_end_offset_minutes__isnull", True),
                            models.Q(
                                ("requested_end_offset_minutes__gt", 0), ("requested_end_offset_minutes__lte", 2880)
                            ),
                            _connector="OR",
                        ),
                        name="shift_change_requested_end_range",
                    ),
                ],
            },
        ),
    ]
