# Generated by Django 5.2.15 on 2026-07-14 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_remove_staffcapability_unique_staff_capability_period_and_more"),
        ("shifts", "0005_shiftchangerequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("work_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("clocked_in", "clocked_in"),
                            ("on_break", "on_break"),
                            ("clocked_out", "clocked_out"),
                            ("pending_correction", "pending_correction"),
                            ("confirmed", "confirmed"),
                            ("void", "void"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("scheduled", "scheduled"),
                            ("unscheduled", "unscheduled"),
                            ("manual", "manual"),
                            ("corrected", "corrected"),
                            ("imported", "imported"),
                        ],
                        default="unscheduled",
                        max_length=32,
                    ),
                ),
                ("scheduled_start_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("scheduled_end_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("scheduled_pattern_name_snapshot", models.CharField(blank=True, max_length=150)),
                ("scheduled_pattern_short_name_snapshot", models.CharField(blank=True, max_length=100)),
                ("actual_clock_in_at", models.DateTimeField(blank=True, null=True)),
                ("actual_clock_out_at", models.DateTimeField(blank=True, null=True)),
                ("actual_start_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("actual_end_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("difference_start_minutes", models.IntegerField(blank=True, null=True)),
                ("difference_end_minutes", models.IntegerField(blank=True, null=True)),
                ("difference_worked_minutes", models.IntegerField(blank=True, null=True)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("manager_note", models.TextField(blank=True)),
                ("staff_note", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="operations.location",
                    ),
                ),
                (
                    "monthly_shift_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="shifts.monthlyshiftassignment",
                    ),
                ),
                (
                    "monthly_shift_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="shifts.monthlyshiftplan",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="shifts.monthlyshiftpublication",
                    ),
                ),
                (
                    "publication_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="shifts.monthlyshiftpublicationassignment",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date", "location__display_order", "staff__employee_code", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("clock_in", "clock_in"),
                            ("break_start", "break_start"),
                            ("break_end", "break_end"),
                            ("clock_out", "clock_out"),
                            ("manual_adjustment", "manual_adjustment"),
                            ("correction_applied", "correction_applied"),
                            ("voided", "voided"),
                            ("confirmed", "confirmed"),
                            ("unconfirmed", "unconfirmed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("offset_minutes", models.IntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[("self", "self"), ("manager", "manager"), ("system", "system")], max_length=20
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attendance_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="events", to="shifts.attendancerecord"
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceCorrectionRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("cancelled", "cancelled"),
                            ("applied", "applied"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("requested_clock_in_at", models.DateTimeField(blank=True, null=True)),
                ("requested_clock_out_at", models.DateTimeField(blank=True, null=True)),
                ("requested_break_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("requested_staff_note", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                ("manager_note", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_corrections_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_corrections_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_corrections_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_corrections_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_correction_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attendance_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_requests",
                        to="shifts.attendancerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["location", "work_date"], name="attendance_location_date_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["staff", "work_date"], name="attendance_staff_date_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["status", "source"], name="attendance_status_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("location", "staff", "work_date"),
                name="unique_active_attendance_record_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scheduled_start_offset_minutes__isnull", True),
                    models.Q(("scheduled_start_offset_minutes__gte", 0), ("scheduled_start_offset_minutes__lt", 2880)),
                    _connector="OR",
                ),
                name="attendance_scheduled_start_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scheduled_end_offset_minutes__isnull", True),
                    models.Q(("scheduled_end_offset_minutes__gt", 0), ("scheduled_end_offset_minutes__lte", 2880)),
                    _connector="OR",
                ),
                name="attendance_scheduled_end_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_start_offset_minutes__isnull", True),
                    models.Q(("actual_start_offset_minutes__gte", 0), ("actual_start_offset_minutes__lt", 2880)),
                    _connector="OR",
                ),
                name="attendance_actual_start_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_end_offset_minutes__isnull", True),
                    models.Q(("actual_end_offset_minutes__gt", 0), ("actual_end_offset_minutes__lte", 2880)),
                    _connector="OR",
                ),
                name="attendance_actual_end_range",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(fields=["attendance_record", "event_type"], name="att_event_record_type_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(fields=["occurred_at"], name="attendance_event_occurred_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendanceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("offset_minutes__gte", 0), ("offset_minutes__lte", 2880)),
                name="attendance_event_offset_range",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancecorrectionrequest",
            index=models.Index(fields=["status", "created_at"], name="attendance_corr_status_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancecorrectionrequest",
            index=models.Index(fields=["requester", "created_at"], name="attendance_corr_requester_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendancecorrectionrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("status__in", ["draft", "submitted", "approved"])),
                fields=("attendance_record",),
                name="unique_open_attendance_correction",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancecorrectionrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("requested_clock_in_at__isnull", True),
                    ("requested_clock_out_at__isnull", True),
                    ("requested_clock_out_at__gt", models.F("requested_clock_in_at")),
                    _connector="OR",
                ),
                name="attendance_corr_clock_out_after_in",
            ),
        ),
    ]
