# Generated by Django 5.2.15 on 2026-07-14 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_remove_staffcapability_unique_staff_capability_period_and_more"),
        ("shifts", "0006_attendancerecord_attendanceevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceClosingPeriod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("review", "review"),
                            ("closed", "closed"),
                            ("reopened", "reopened"),
                            ("archived", "archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("validation_fingerprint", models.CharField(blank=True, max_length=64)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_periods_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_periods_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_periods",
                        to="operations.location",
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_periods_reopened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_periods_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "location__display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceClosingRecordSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("location_code_snapshot", models.CharField(max_length=50)),
                ("location_name_snapshot", models.CharField(max_length=150)),
                ("staff_display_name_snapshot", models.CharField(max_length=150)),
                ("employee_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("work_date", models.DateField()),
                ("status_snapshot", models.CharField(max_length=32)),
                ("source_snapshot", models.CharField(max_length=32)),
                ("scheduled_start_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("scheduled_end_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("scheduled_pattern_name_snapshot", models.CharField(blank=True, max_length=150)),
                ("scheduled_pattern_short_name_snapshot", models.CharField(blank=True, max_length=100)),
                ("actual_clock_in_at", models.DateTimeField(blank=True, null=True)),
                ("actual_clock_out_at", models.DateTimeField(blank=True, null=True)),
                ("actual_start_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("actual_end_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("difference_start_minutes", models.IntegerField(blank=True, null=True)),
                ("difference_end_minutes", models.IntegerField(blank=True, null=True)),
                ("difference_worked_minutes", models.IntegerField(blank=True, null=True)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("manager_note_snapshot", models.TextField(blank=True)),
                ("staff_note_snapshot", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_by_display_name_snapshot", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closing_snapshots",
                        to="shifts.attendancerecord",
                    ),
                ),
                (
                    "closing_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_snapshots",
                        to="shifts.attendanceclosingperiod",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_snapshots_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_snapshots",
                        to="operations.location",
                    ),
                ),
                (
                    "monthly_shift_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_snapshots",
                        to="shifts.monthlyshiftassignment",
                    ),
                ),
                (
                    "monthly_shift_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_snapshots",
                        to="shifts.monthlyshiftplan",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_snapshots",
                        to="shifts.monthlyshiftpublication",
                    ),
                ),
                (
                    "publication_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_snapshots",
                        to="shifts.monthlyshiftpublicationassignment",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["work_date", "employee_code_snapshot", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceClosingStaffSummary",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("staff_display_name_snapshot", models.CharField(max_length=150)),
                ("employee_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("scheduled_days", models.PositiveIntegerField(default=0)),
                ("attendance_record_days", models.PositiveIntegerField(default=0)),
                ("worked_days", models.PositiveIntegerField(default=0)),
                ("unscheduled_work_days", models.PositiveIntegerField(default=0)),
                ("scheduled_minutes", models.PositiveIntegerField(default=0)),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                ("late_count", models.PositiveIntegerField(default=0)),
                ("early_leave_count", models.PositiveIntegerField(default=0)),
                ("missing_clock_in_count", models.PositiveIntegerField(default=0)),
                ("missing_clock_out_count", models.PositiveIntegerField(default=0)),
                ("open_break_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("confirmed_count", models.PositiveIntegerField(default=0)),
                ("unconfirmed_count", models.PositiveIntegerField(default=0)),
                ("pending_correction_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closing_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_summaries",
                        to="shifts.attendanceclosingperiod",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_closing_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee_code_snapshot", "staff_display_name_snapshot", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="attendanceclosingperiod",
            index=models.Index(fields=["location", "year", "month"], name="att_close_period_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceclosingperiod",
            index=models.Index(fields=["status", "is_active"], name="att_close_period_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendanceclosingperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("location", "year", "month"),
                name="uniq_active_att_close_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceclosingperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 2000), ("year__lte", 2100)), name="att_close_year_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceclosingperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)), name="att_close_month_range"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceclosingrecordsnapshot",
            index=models.Index(fields=["closing_period", "work_date"], name="att_close_snap_date_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceclosingrecordsnapshot",
            index=models.Index(fields=["staff", "work_date"], name="att_close_snap_staff_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendanceclosingrecordsnapshot",
            constraint=models.UniqueConstraint(
                fields=("closing_period", "staff", "work_date", "location"), name="uniq_att_close_snapshot_day"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceclosingstaffsummary",
            index=models.Index(fields=["closing_period", "staff"], name="att_close_sum_staff_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendanceclosingstaffsummary",
            constraint=models.UniqueConstraint(fields=("closing_period", "staff"), name="uniq_att_close_staff_sum"),
        ),
    ]
