# Generated by Django 5.2.15 on 2026-07-20 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_remove_staffcapability_unique_staff_capability_period_and_more"),
        ("shifts", "0007_attendanceclosingperiod_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborCostEstimatePeriod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("review", "review"),
                            ("finalized", "finalized"),
                            ("reopened", "reopened"),
                            ("archived", "archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("validation_fingerprint", models.CharField(blank=True, max_length=64)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "attendance_closing_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_estimate_periods",
                        to="shifts.attendanceclosingperiod",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_estimate_periods_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_estimate_periods_finalized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_estimate_periods",
                        to="operations.location",
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_estimate_periods_reopened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_estimate_periods_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "location__display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaborCostEstimateRecordSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("location_code_snapshot", models.CharField(max_length=50)),
                ("location_name_snapshot", models.CharField(max_length=150)),
                ("staff_display_name_snapshot", models.CharField(max_length=150)),
                ("employee_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("work_date", models.DateField()),
                ("employment_type_snapshot", models.CharField(max_length=32)),
                (
                    "base_hourly_rate_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "fixed_monthly_amount_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("worked_hours_decimal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("base_pay", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("allowance_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("estimated_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance_closing_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_snapshots",
                        to="shifts.attendanceclosingrecordsnapshot",
                    ),
                ),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_snapshots",
                        to="shifts.attendancerecord",
                    ),
                ),
                (
                    "estimate_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_snapshots",
                        to="shifts.laborcostestimateperiod",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_record_snapshots",
                        to="operations.location",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_record_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["work_date", "employee_code_snapshot", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaborCostEstimateStaffSummary",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("staff_display_name_snapshot", models.CharField(max_length=150)),
                ("employee_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("employment_type_snapshot", models.CharField(max_length=32)),
                (
                    "base_hourly_rate_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "fixed_monthly_amount_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("worked_days", models.PositiveIntegerField(default=0)),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("worked_hours_decimal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("base_pay_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("allowance_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("estimated_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "estimate_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_summaries",
                        to="shifts.laborcostestimateperiod",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_staff_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee_code_snapshot", "staff_display_name_snapshot", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffAllowanceAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=150)),
                (
                    "allowance_type",
                    models.CharField(
                        choices=[
                            ("per_worked_day", "per_worked_day"),
                            ("per_worked_hour", "per_worked_hour"),
                            ("fixed_monthly", "fixed_monthly"),
                            ("manual", "manual"),
                        ],
                        default="per_worked_day",
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_allowance_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_allowance_assignments",
                        to="operations.location",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allowance_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_allowance_assignments_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["location__display_order", "staff__employee_code", "code", "-valid_from", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaborCostEstimateAllowanceSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("staff_display_name_snapshot", models.CharField(max_length=150)),
                ("employee_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("code_snapshot", models.CharField(max_length=50)),
                ("name_snapshot", models.CharField(max_length=150)),
                ("allowance_type_snapshot", models.CharField(max_length=32)),
                ("amount_snapshot", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("estimated_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_allowance_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estimate_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowance_snapshots",
                        to="shifts.laborcostestimateperiod",
                    ),
                ),
                (
                    "allowance_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_snapshots",
                        to="shifts.staffallowanceassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["employee_code_snapshot", "code_snapshot", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffCompensationProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[("hourly", "hourly"), ("monthly_fixed", "monthly_fixed"), ("other", "other")],
                        default="hourly",
                        max_length=32,
                    ),
                ),
                ("base_hourly_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("fixed_monthly_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_compensation_profiles_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_compensation_profiles",
                        to="operations.location",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compensation_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_compensation_profiles_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["location__display_order", "staff__employee_code", "-valid_from", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="laborcostestimateperiod",
            index=models.Index(fields=["location", "year", "month"], name="labor_period_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="laborcostestimateperiod",
            index=models.Index(fields=["status", "is_active"], name="labor_period_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="laborcostestimateperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("location", "year", "month"),
                name="uniq_active_labor_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="laborcostestimateperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 2000), ("year__lte", 2100)), name="labor_period_year_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="laborcostestimateperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)), name="labor_period_month_range"
            ),
        ),
        migrations.AddIndex(
            model_name="laborcostestimaterecordsnapshot",
            index=models.Index(fields=["estimate_period", "work_date"], name="labor_snap_date_idx"),
        ),
        migrations.AddIndex(
            model_name="laborcostestimaterecordsnapshot",
            index=models.Index(fields=["staff", "work_date"], name="labor_snap_staff_idx"),
        ),
        migrations.AddConstraint(
            model_name="laborcostestimaterecordsnapshot",
            constraint=models.UniqueConstraint(
                fields=("estimate_period", "staff", "work_date", "location"), name="uniq_labor_snapshot_day"
            ),
        ),
        migrations.AddIndex(
            model_name="laborcostestimatestaffsummary",
            index=models.Index(fields=["estimate_period", "staff"], name="labor_sum_staff_idx"),
        ),
        migrations.AddConstraint(
            model_name="laborcostestimatestaffsummary",
            constraint=models.UniqueConstraint(fields=("estimate_period", "staff"), name="uniq_labor_staff_sum"),
        ),
        migrations.AddIndex(
            model_name="staffallowanceassignment",
            index=models.Index(fields=["location", "staff", "code", "is_active"], name="allowance_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="staffallowanceassignment",
            index=models.Index(fields=["valid_from", "valid_to"], name="allowance_period_idx"),
        ),
        migrations.AddConstraint(
            model_name="staffallowanceassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True), ("valid_from__lte", models.F("valid_to")), _connector="OR"
                ),
                name="allowance_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffallowanceassignment",
            constraint=models.CheckConstraint(condition=models.Q(("amount__gte", 0)), name="allowance_amount_gte0"),
        ),
        migrations.AddIndex(
            model_name="laborcostestimateallowancesnapshot",
            index=models.Index(fields=["estimate_period", "staff"], name="labor_allow_staff_idx"),
        ),
        migrations.AddIndex(
            model_name="laborcostestimateallowancesnapshot",
            index=models.Index(fields=["allowance_assignment"], name="labor_allow_assign_idx"),
        ),
        migrations.AddIndex(
            model_name="staffcompensationprofile",
            index=models.Index(fields=["location", "staff", "is_active"], name="comp_profile_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="staffcompensationprofile",
            index=models.Index(fields=["valid_from", "valid_to"], name="comp_profile_period_idx"),
        ),
        migrations.AddConstraint(
            model_name="staffcompensationprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True), ("valid_from__lte", models.F("valid_to")), _connector="OR"
                ),
                name="comp_profile_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffcompensationprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_hourly_rate__isnull", True), ("base_hourly_rate__gte", 0), _connector="OR"),
                name="comp_profile_hourly_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffcompensationprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fixed_monthly_amount__isnull", True), ("fixed_monthly_amount__gte", 0), _connector="OR"
                ),
                name="comp_profile_fixed_gte0",
            ),
        ),
    ]
