# Generated by Django 5.2.15 on 2026-07-20 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_remove_staffcapability_unique_staff_capability_period_and_more"),
        ("shifts", "0008_laborcostestimateperiod_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborCostBudgetPeriod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("budget_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("warning_threshold_percent", models.DecimalField(decimal_places=2, default=90, max_digits=6)),
                ("critical_threshold_percent", models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("review", "review"),
                            ("approved", "approved"),
                            ("reopened", "reopened"),
                            ("archived", "archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("validation_fingerprint", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_periods_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_periods_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_periods",
                        to="operations.location",
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_periods_reopened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_monthly_shift_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_periods",
                        to="shifts.monthlyshiftplan",
                    ),
                ),
                (
                    "source_publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_periods",
                        to="shifts.monthlyshiftpublication",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_periods_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "location__display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaborCostBudgetDailySummary",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("work_date", models.DateField()),
                ("planned_staff_count", models.PositiveIntegerField(default=0)),
                ("planned_worked_minutes", models.PositiveIntegerField(default=0)),
                ("planned_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("actual_staff_count", models.PositiveIntegerField(default=0)),
                ("actual_worked_minutes", models.PositiveIntegerField(default=0)),
                ("actual_estimated_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("actual_plan_variance_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "actual_plan_variance_percent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
                ),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to="shifts.laborcostbudgetperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["work_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaborCostBudgetAllowanceSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("staff_display_name_snapshot", models.CharField(max_length=150)),
                ("employee_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("code_snapshot", models.CharField(max_length=50)),
                ("name_snapshot", models.CharField(max_length=150)),
                ("allowance_type_snapshot", models.CharField(max_length=32)),
                ("amount_snapshot", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("planned_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allowance_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_snapshots",
                        to="shifts.staffallowanceassignment",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_allowance_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowance_snapshots",
                        to="shifts.laborcostbudgetperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["employee_code_snapshot", "code_snapshot", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaborCostBudgetPlanRecordSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("work_date", models.DateField()),
                ("location_code_snapshot", models.CharField(max_length=50)),
                ("location_name_snapshot", models.CharField(max_length=150)),
                ("staff_display_name_snapshot", models.CharField(max_length=150)),
                ("employee_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("plan_source_snapshot", models.CharField(max_length=20)),
                ("employment_type_snapshot", models.CharField(max_length=32)),
                (
                    "base_hourly_rate_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "fixed_monthly_amount_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("planned_start_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("planned_end_offset_minutes", models.IntegerField(blank=True, null=True)),
                ("planned_worked_minutes", models.PositiveIntegerField(default=0)),
                ("planned_hours_decimal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("planned_base_pay", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("planned_daily_allowance", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("planned_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_record_snapshots",
                        to="shifts.laborcostbudgetperiod",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_plan_snapshots",
                        to="operations.location",
                    ),
                ),
                (
                    "monthly_shift_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_plan_snapshots",
                        to="shifts.monthlyshiftassignment",
                    ),
                ),
                (
                    "monthly_shift_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_plan_snapshots",
                        to="shifts.monthlyshiftplan",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_plan_snapshots",
                        to="shifts.monthlyshiftpublication",
                    ),
                ),
                (
                    "publication_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_plan_snapshots",
                        to="shifts.monthlyshiftpublicationassignment",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_plan_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["work_date", "employee_code_snapshot", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaborCostBudgetStaffSummary",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("staff_display_name_snapshot", models.CharField(max_length=150)),
                ("employee_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("employment_type_snapshot", models.CharField(max_length=32)),
                (
                    "base_hourly_rate_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "fixed_monthly_amount_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("planned_worked_days", models.PositiveIntegerField(default=0)),
                ("planned_worked_minutes", models.PositiveIntegerField(default=0)),
                ("planned_hours_decimal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("planned_hourly_base_pay", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("planned_fixed_monthly_pay", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("planned_allowance_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("planned_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("actual_worked_minutes", models.PositiveIntegerField(default=0)),
                ("actual_base_pay_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("actual_allowance_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("actual_estimated_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("actual_plan_variance_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "actual_plan_variance_percent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
                ),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_summaries",
                        to="shifts.laborcostbudgetperiod",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_cost_budget_staff_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee_code_snapshot", "staff_display_name_snapshot", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="laborcostbudgetperiod",
            index=models.Index(fields=["location", "year", "month"], name="labor_budget_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="laborcostbudgetperiod",
            index=models.Index(fields=["status", "is_active"], name="labor_budget_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("location", "year", "month"),
                name="uniq_active_labor_budget",
            ),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 2000), ("year__lte", 2100)), name="labor_budget_year_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)), name="labor_budget_month_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("budget_amount__gte", 0)), name="labor_budget_amount_gte0"
            ),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("warning_threshold_percent__gte", 0)), name="labor_budget_warn_gte0"
            ),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("critical_threshold_percent__gte", models.F("warning_threshold_percent"))),
                name="labor_budget_critical_gte_warn",
            ),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("critical_threshold_percent__lte", 999.99)), name="labor_budget_critical_lte999"
            ),
        ),
        migrations.AddIndex(
            model_name="laborcostbudgetdailysummary",
            index=models.Index(fields=["budget_period", "work_date"], name="labor_budget_daily_idx"),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetdailysummary",
            constraint=models.UniqueConstraint(
                fields=("budget_period", "work_date"), name="uniq_labor_budget_daily_sum"
            ),
        ),
        migrations.AddIndex(
            model_name="laborcostbudgetallowancesnapshot",
            index=models.Index(fields=["budget_period", "staff"], name="labor_budget_allow_staff_idx"),
        ),
        migrations.AddIndex(
            model_name="laborcostbudgetallowancesnapshot",
            index=models.Index(fields=["allowance_assignment"], name="labor_budget_allow_idx"),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetallowancesnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("allowance_assignment__isnull", False)),
                fields=("budget_period", "staff", "allowance_assignment"),
                name="uniq_labor_budget_allow_assign",
            ),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetallowancesnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("allowance_assignment__isnull", True)),
                fields=("budget_period", "staff", "code_snapshot", "allowance_type_snapshot"),
                name="uniq_labor_budget_allow_code",
            ),
        ),
        migrations.AddIndex(
            model_name="laborcostbudgetplanrecordsnapshot",
            index=models.Index(fields=["budget_period", "work_date"], name="labor_budget_plan_date_idx"),
        ),
        migrations.AddIndex(
            model_name="laborcostbudgetplanrecordsnapshot",
            index=models.Index(fields=["staff", "work_date"], name="labor_budget_plan_staff_idx"),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetplanrecordsnapshot",
            constraint=models.UniqueConstraint(
                fields=("budget_period", "staff", "work_date", "location"), name="uniq_labor_budget_plan_day"
            ),
        ),
        migrations.AddIndex(
            model_name="laborcostbudgetstaffsummary",
            index=models.Index(fields=["budget_period", "staff"], name="labor_budget_staff_sum_idx"),
        ),
        migrations.AddConstraint(
            model_name="laborcostbudgetstaffsummary",
            constraint=models.UniqueConstraint(fields=("budget_period", "staff"), name="uniq_labor_budget_staff_sum"),
        ),
    ]
