# Generated by Django 5.2.15 on 2026-07-20 10:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_remove_staffcapability_unique_staff_capability_period_and_more"),
        ("shifts", "0009_laborcostbudgetperiod_laborcostbudgetdailysummary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueBudgetPeriod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("review", "review"),
                            ("approved", "approved"),
                            ("reopened", "reopened"),
                            ("archived", "archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("validation_fingerprint", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_budget_periods_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_budget_periods_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_budget_periods",
                        to="operations.location",
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_budget_periods_reopened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_budget_periods_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "location__display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueActualPeriod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("review", "review"),
                            ("finalized", "finalized"),
                            ("reopened", "reopened"),
                            ("archived", "archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("validation_fingerprint", models.CharField(blank=True, max_length=64)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_actual_periods_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_actual_periods_finalized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "labor_cost_budget_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_actual_periods",
                        to="shifts.laborcostbudgetperiod",
                    ),
                ),
                (
                    "labor_cost_estimate_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_actual_periods",
                        to="shifts.laborcostestimateperiod",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_actual_periods",
                        to="operations.location",
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_actual_periods_reopened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_actual_periods_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revenue_budget_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_actual_periods",
                        to="shifts.revenuebudgetperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "location__display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="code must contain only letters, numbers, hyphens, and underscores.",
                                regex="^[A-Za-z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("short_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_categories_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_categories",
                        to="operations.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_categories_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["location__display_order", "display_order", "code", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueBudgetLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category_code_snapshot", models.CharField(max_length=50)),
                ("category_name_snapshot", models.CharField(max_length=150)),
                ("budget_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="shifts.revenuebudgetperiod",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_lines",
                        to="shifts.revenuecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "category_code_snapshot", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueActualLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category_code_snapshot", models.CharField(max_length=50)),
                ("category_name_snapshot", models.CharField(max_length=150)),
                ("actual_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "manual"), ("imported", "imported"), ("adjusted", "adjusted")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actual_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="shifts.revenueactualperiod",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actual_lines",
                        to="shifts.revenuecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "category_code_snapshot", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenuePerformanceSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("location_code_snapshot", models.CharField(max_length=50)),
                ("location_name_snapshot", models.CharField(max_length=150)),
                ("revenue_budget_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("revenue_actual_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("revenue_variance_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "revenue_attainment_percent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
                ),
                ("labor_budget_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("planned_labor_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("actual_labor_cost_estimate", models.DecimalField(decimal_places=2, max_digits=14)),
                ("budget_labor_cost_ratio", models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                (
                    "planned_labor_cost_ratio_to_budget_revenue",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
                ),
                (
                    "planned_labor_cost_ratio_to_actual_revenue",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
                ),
                ("actual_labor_cost_ratio", models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ("planned_vs_labor_budget_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("actual_vs_labor_budget_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("actual_vs_planned_labor_cost_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("budget_content_hash", models.CharField(blank=True, max_length=64)),
                ("labor_budget_content_hash", models.CharField(blank=True, max_length=64)),
                ("labor_estimate_content_hash", models.CharField(blank=True, max_length=64)),
                ("content_hash", models.CharField(max_length=64)),
                ("validation_fingerprint", models.CharField(max_length=64)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actual_period",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_snapshot",
                        to="shifts.revenueactualperiod",
                    ),
                ),
                (
                    "labor_cost_budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_performance_snapshots",
                        to="shifts.laborcostbudgetperiod",
                    ),
                ),
                (
                    "labor_cost_estimate_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_performance_snapshots",
                        to="shifts.laborcostestimateperiod",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_performance_snapshots",
                        to="operations.location",
                    ),
                ),
                (
                    "revenue_budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performance_snapshots",
                        to="shifts.revenuebudgetperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "location_code_snapshot"],
            },
        ),
        migrations.CreateModel(
            name="RevenuePerformanceLineSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category_code_snapshot", models.CharField(max_length=50)),
                ("category_name_snapshot", models.CharField(max_length=150)),
                ("budget_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("actual_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("variance_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("attainment_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_line_snapshots",
                        to="shifts.revenuecategory",
                    ),
                ),
                (
                    "performance_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_snapshots",
                        to="shifts.revenueperformancesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "category_code_snapshot", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="revenuebudgetperiod",
            index=models.Index(fields=["location", "year", "month"], name="revenue_budget_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="revenuebudgetperiod",
            index=models.Index(fields=["status", "is_active"], name="revenue_budget_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="revenuebudgetperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("location", "year", "month"),
                name="uniq_active_revenue_budget",
            ),
        ),
        migrations.AddConstraint(
            model_name="revenuebudgetperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 2000), ("year__lte", 2100)), name="revenue_budget_year_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="revenuebudgetperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)), name="revenue_budget_month_range"
            ),
        ),
        migrations.AddIndex(
            model_name="revenueactualperiod",
            index=models.Index(fields=["location", "year", "month"], name="revenue_actual_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="revenueactualperiod",
            index=models.Index(fields=["status", "is_active"], name="revenue_actual_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="revenueactualperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("location", "year", "month"),
                name="uniq_active_revenue_actual",
            ),
        ),
        migrations.AddConstraint(
            model_name="revenueactualperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 2000), ("year__lte", 2100)), name="revenue_actual_year_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="revenueactualperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)), name="revenue_actual_month_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="revenuecategory",
            constraint=models.UniqueConstraint(fields=("location", "code"), name="uniq_revenue_category_code"),
        ),
        migrations.AddConstraint(
            model_name="revenuecategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_order__gte", 0)), name="revenue_category_order_gte0"
            ),
        ),
        migrations.AddIndex(
            model_name="revenuebudgetline",
            index=models.Index(fields=["budget_period", "is_active"], name="revenue_budget_line_idx"),
        ),
        migrations.AddConstraint(
            model_name="revenuebudgetline",
            constraint=models.UniqueConstraint(fields=("budget_period", "category"), name="uniq_revenue_budget_line"),
        ),
        migrations.AddConstraint(
            model_name="revenuebudgetline",
            constraint=models.CheckConstraint(
                condition=models.Q(("budget_amount__gte", 0)), name="revenue_budget_amount_gte0"
            ),
        ),
        migrations.AddConstraint(
            model_name="revenuebudgetline",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_order__gte", 0)), name="revenue_budget_order_gte0"
            ),
        ),
        migrations.AddIndex(
            model_name="revenueactualline",
            index=models.Index(fields=["actual_period", "is_active"], name="revenue_actual_line_idx"),
        ),
        migrations.AddConstraint(
            model_name="revenueactualline",
            constraint=models.UniqueConstraint(fields=("actual_period", "category"), name="uniq_revenue_actual_line"),
        ),
        migrations.AddConstraint(
            model_name="revenueactualline",
            constraint=models.CheckConstraint(
                condition=models.Q(("actual_amount__gte", 0)), name="revenue_actual_amount_gte0"
            ),
        ),
        migrations.AddConstraint(
            model_name="revenueactualline",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_order__gte", 0)), name="revenue_actual_order_gte0"
            ),
        ),
        migrations.AddIndex(
            model_name="revenueperformancesnapshot",
            index=models.Index(fields=["location", "year", "month"], name="revenue_perf_lookup_idx"),
        ),
        migrations.AddConstraint(
            model_name="revenueperformancelinesnapshot",
            constraint=models.UniqueConstraint(
                fields=("performance_snapshot", "category_code_snapshot"), name="uniq_revenue_perf_line"
            ),
        ),
    ]
